import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Auth.module.scss'
import Link from 'next/link'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faEye } from '@fortawesome/free-solid-svg-icons'

export default function Login() {
  return (
    <>
      <Head>
        <title>Kejetia Traders | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.content}>
          <nav>
            <Link href="/">
              <Image 
                src="/assets/images/logo-white.png" 
                alt="logo" 
                width={200} 
                height={200}
                className={styles.logo}
              />
            </Link>
          </nav>
          <div className={styles.main}>
            <div className={styles.left}>
              <h1>The <span>No. 1</span></h1>
              <h1>TLC Trading</h1>
              <h1>Platform</h1>
            </div>
            <div className={styles.right}>
              <p className={styles.mobileHeading}>The No. 1 TLC Trading Platform</p>
              <form>
                <h6 className={styles.title}>Sign in</h6>
                <p className={styles.tagline}>Welcome to Kejetia Traders</p>
                <div className={styles.errorBox}>
                </div>
                <div className={styles.inputGroup}>
                  <label htmlFor="email">Email</label>
                  <input 
                    type="email" 
                    placeholder="charity.darko@turntabl.io"
                    required 
                  />
                </div>
                <div className={styles.inputGroupPassword}>
                  <label htmlFor="password">Password</label>
                  <div className={styles.passwordBox}>
                    <input 
                      required
                    />
                    <button type="button">
                      <FontAwesomeIcon icon={faEye} className={styles.icon} />
                    </button>
                  </div>
                </div>
                <div className={styles.rememberForgotPassword}>
                  <div>
                    <input type="checkbox" />
                    <label htmlFor="remember_me">Remember me</label>
                  </div>
                  <a>Forgot Password?</a>
                </div>
                <button type="submit" className={styles.submitBox}>
                  Sign In
                </button>
                <p className={styles.noAccount}>Don&apos;t have an account? <Link href="register">Sign up</Link></p>
              </form>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
